name: Check commit message

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main

jobs:
  check_commit_message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check commit message format
        run: |
          commits=$(git log --format=%B -n 1)
          if ! [[ "$commits" =~ ^JIRA-[0-9]+ ]]; then
            echo "Error: Commit message must start with a JIRA issue key (e.g., JIRA-12345)."
            exit 1
          fi
